interface StayFeatureVisualProps { index: number; }

const BookingVisual = () => <div className="feature-art booking-art" aria-hidden="true"><div className="feature-window-bar"><i /><i /><i /><span>14-day booking view</span></div><div className="mini-calendar-head"><b>ROOM</b>{["12", "13", "14", "15", "16"].map((date) => <span key={date}>{date}</span>)}</div><div className="mini-calendar-row"><b>304</b><i /><i /><i /><i /><i /><span>Amara Silva · Paid</span></div><div className="mini-calendar-row"><b>405</b><i /><i /><i /><i /><i /><span>Noah Williams</span></div><div className="feature-float-chip">+ Direct booking</div></div>;

const GuestVisual = () => <div className="feature-art guest-art" aria-hidden="true"><div className="guest-art-person"><i>AS<span>VIP</span></i><div><strong>Amara Silva</strong><small>Returning guest · 4 stays</small></div></div><div className="guest-art-tags"><span>Quiet room</span><span>Vegetarian</span><span>High floor</span></div><div className="guest-art-stats"><div><small>LAST STAY</small><strong>Ocean Suite</strong></div><div><small>LIFETIME VALUE</small><strong>LKR 684K</strong></div></div><div className="feature-float-chip">✦ Preferences remembered</div></div>;

const HousekeepingVisual = () => <div className="feature-art housekeeping-art" aria-hidden="true"><div className="housekeeping-art-head"><div><strong>Floor 03</strong><small>8 of 10 ready</small></div><span>LIVE</span></div><div className="housekeeping-room-grid">{[["301", "ready"], ["302", "cleaning"], ["303", "ready"], ["304", "priority"], ["305", "occupied"], ["306", "ready"]].map(([room,status]) => <div className={status} key={room}><strong>{room}</strong><span>{status}</span></div>)}</div><div className="feature-float-chip">✓ Room 304 inspected</div></div>;

const DepositVisual = () => <div className="feature-art deposit-art" aria-hidden="true"><div className="deposit-booking"><span>BK-10842</span><strong>Ocean Suite · 3 nights</strong><small>Amara Silva · Direct</small></div><div className="deposit-flow"><div><i>1</i><span>Reserved</span></div><b /><div><i>2</i><span>Link sent</span></div><b /><div className="done"><i>✓</i><span>Paid</span></div></div><div className="deposit-total"><span>DEPOSIT SECURED</span><strong>LKR 93,375</strong></div><div className="feature-float-chip">0 unpaid room holds</div></div>;

const ComplianceVisual = () => <div className="feature-art compliance-art" aria-hidden="true"><div className="compliance-sheet"><header><span>TOURIST POLICE</span><b>Synced</b></header>{[["Amara Silva", "SL", "✓"], ["Mei Tan", "SG", "✓"], ["Noah Williams", "UK", "···"]].map(([name,country,status]) => <div key={name}><i>{country}</i><strong>{name}</strong><span>{status}</span></div>)}</div><div className="compliance-cloud"><i>☁</i><strong>Microsoft 365</strong><span>Last sync · 11:42 AM</span></div><div className="feature-float-chip">22 records updated</div></div>;

const FinanceVisual = () => <div className="feature-art finance-art" aria-hidden="true"><div className="invoice-paper"><header><div><strong>Nami Stay</strong><small>INVOICE #INV-2841</small></div><b>PAID</b></header><div><span>Room total</span><strong>LKR 145,500</strong></div><div><span>Service charge</span><strong>LKR 14,550</strong></div><div><span>VAT & SSCL</span><strong>LKR 26,700</strong></div><footer><span>TOTAL</span><strong>LKR 186,750</strong></footer></div><div className="finance-actions"><span>PDF</span><span>WhatsApp</span></div><div className="feature-float-chip">✓ Branded & tax-ready</div></div>;

const visuals = [BookingVisual, GuestVisual, HousekeepingVisual, DepositVisual, ComplianceVisual, FinanceVisual];

export const StayFeatureVisual = ({ index }: StayFeatureVisualProps) => { const Visual = visuals[index] ?? BookingVisual; return <Visual />; };
