import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How NamiOS and DesignNetrix collect, use, protect, retain, and share personal data."
};

const PrivacyPage = () => (
  <main className="legal-page">
    <header className="legal-hero">
      <div className="container"><span className="eyebrow">Legal · Privacy</span><h1>Privacy Policy</h1><p>How NamiOS and DesignNetrix handle personal data across our website, enquiries, trials, and subscription services.</p><small>Effective: 2 August 2026 · Last updated: 2 August 2026</small></div>
    </header>
    <div className="container legal-layout">
      <aside className="legal-nav" aria-label="Privacy policy contents">
        <strong>On this page</strong>
        <a href="#scope">Scope</a><a href="#data">Data we collect</a><a href="#use">How we use data</a><a href="#sharing">Sharing</a><a href="#retention">Retention and security</a><a href="#rights">Your rights</a><a href="#contact-privacy">Contact</a>
      </aside>
      <article className="legal-content">
        <section id="scope"><span>01</span><h2>Who we are and the scope of this policy</h2><p>NamiOS is a hospitality operating platform developed and operated by DesignNetrix in Colombo, Sri Lanka. This policy applies when you visit the NamiOS public website, contact us, request a demonstration or trial, subscribe to NamiOS, or use an account supplied by a subscribing property.</p><p>For guest, employee, and property records entered by a subscribing hotel or business, that customer normally decides why and how the information is used. In that context, the customer is responsible for its instructions and DesignNetrix provides NamiOS as its service provider, subject to the applicable subscription agreement and data-processing terms.</p></section>
        <section id="data"><span>02</span><h2>Personal data we may collect</h2><ul><li><strong>Contact and enquiry data:</strong> name, business email, telephone number, property name, role, and enquiry content.</li><li><strong>Account and subscription data:</strong> login identity, role, property configuration, plan, invoices, support requests, and account activity.</li><li><strong>Hospitality records supplied by customers:</strong> guest identity and contact information, reservation details, identification references, preferences, payment status, folios, staff records, attendance, and payroll data where the relevant application is used.</li><li><strong>Technical data:</strong> device, browser, IP address, security events, timestamps, diagnostic logs, and essential cookie information.</li><li><strong>Payment information:</strong> transaction references and payment status. Card or bank credentials may be processed directly by an independent payment provider and are not necessarily stored by NamiOS.</li></ul></section>
        <section id="use"><span>03</span><h2>Why we use personal data</h2><p>We use personal data to respond to enquiries; prepare demos and trials; create and secure accounts; deliver, maintain, support, and improve NamiOS; process subscriptions and payments; prevent abuse; troubleshoot problems; communicate service information; and comply with lawful obligations.</p><p>We process personal data only where an appropriate legal basis or customer instruction applies. We do not sell personal data. We do not use hotel guest or employee records for unrelated advertising.</p></section>
        <section><span>04</span><h2>Cookies and communications</h2><p>The public website uses essential technologies needed for security, navigation, and performance. If non-essential analytics or advertising cookies are introduced, we will provide appropriate notice and choices before using them where required.</p><p>You can opt out of marketing communications through the method provided in the message or by contacting us. Operational, billing, security, and account messages may still be sent when needed to deliver the service.</p></section>
        <section id="sharing"><span>05</span><h2>When information may be shared</h2><p>We may share limited information with infrastructure, communications, support, payment, professional-advisory, and security providers that help us operate NamiOS; with a customer that administers your NamiOS account; when required by a valid legal process; or during a legitimate business reorganisation subject to suitable safeguards.</p><p>Where personal data is processed outside Sri Lanka, DesignNetrix will use the instruments, contractual arrangements, and safeguards required by applicable Sri Lankan law and regulatory directions.</p></section>
        <section id="retention"><span>06</span><h2>Retention and security</h2><p>We retain information only for as long as reasonably required for the purpose collected, the customer agreement, security, dispute resolution, accounting, or applicable law. Customer data is returned or deleted in line with the service agreement, subject to lawful retention and backup cycles.</p><p>We use administrative, technical, and organisational safeguards designed to protect confidentiality, integrity, and availability. No internet service can guarantee absolute security, so customers and users must also protect credentials and promptly report suspected misuse.</p></section>
        <section id="rights"><span>07</span><h2>Your choices and rights</h2><p>Depending on the applicable law and context, you may have rights to request access to personal data, correction of inaccurate information, erasure where permitted, withdrawal of consent, or review of certain processing decisions. When a property controls the relevant data, requests should usually be directed to that property first; we will assist it where required.</p><p>You may also contact Sri Lanka’s Data Protection Authority. Rights and procedures remain subject to the Personal Data Protection Act No. 9 of 2022, as amended, applicable commencement orders, and regulatory guidance.</p></section>
        <section><span>08</span><h2>Children, changes, and other websites</h2><p>NamiOS is a business service and is not directed to children. Hospitality customers are responsible for ensuring they have an appropriate basis for any child or guardian information required for a booking or legal record.</p><p>Links to third-party services are governed by their own policies. We may update this policy as the product, service providers, or law changes. Material changes will be highlighted through the website, account, or direct notice where appropriate.</p></section>
        <section id="contact-privacy" className="legal-contact"><span>09</span><h2>Privacy contact</h2><p>For privacy questions or requests, email <a href="mailto:hellonamios@outlook.com?subject=NamiOS%20privacy%20request">hellonamios@outlook.com</a> with “NamiOS privacy request” in the subject. We may need to verify your identity and relationship to the relevant property before acting.</p><p>NamiOS by DesignNetrix · Colombo, Sri Lanka · <a href="https://www.designnetrix.com/" target="_blank" rel="noreferrer">designnetrix.com</a></p></section>
        <div className="legal-reference"><strong>Legal references</strong><p>This policy is designed with reference to Sri Lanka’s Personal Data Protection Act No. 9 of 2022, the Personal Data Protection (Amendment) Act No. 22 of 2025, and relevant Consumer Affairs Authority e-commerce directions. It should be read with the applicable NamiOS service agreement.</p></div>
      </article>
    </div>
  </main>
);

export default PrivacyPage;
