import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Terms governing access to the NamiOS website, trials, subscriptions, annual plans, and hospitality software services."
};

const TermsPage = () => (
  <main className="legal-page">
    <header className="legal-hero">
      <div className="container"><span className="eyebrow">Legal · Service</span><h1>Terms and Conditions</h1><p>The ground rules for using the NamiOS website, trials, subscriptions, applications, and related DesignNetrix services.</p><small>Effective: 2 August 2026 · Last updated: 2 August 2026</small></div>
    </header>
    <div className="container legal-layout">
      <aside className="legal-nav" aria-label="Terms contents"><strong>On this page</strong><a href="#agreement">Agreement</a><a href="#plans">Plans and billing</a><a href="#customer">Customer responsibilities</a><a href="#data-terms">Data and IP</a><a href="#service">Service terms</a><a href="#liability">Liability</a><a href="#law">Sri Lankan law</a></aside>
      <article className="legal-content">
        <section id="agreement"><span>01</span><h2>Agreement and eligibility</h2><p>These Terms govern access to the public NamiOS website and the NamiOS subscription service provided by DesignNetrix. By creating an account, accepting an order form, beginning a trial, paying an invoice, or using the service, you agree to these Terms and any applicable proposal, order form, data-processing terms, or service schedule.</p><p>You must have legal capacity and, when acting for a business, authority to bind that business. Electronic acceptance, records, and communications may be used in accordance with Sri Lanka’s Electronic Transactions Act No. 19 of 2006, as amended.</p></section>
        <section id="plans"><span>02</span><h2>Trials, plans, pricing, and renewals</h2><ul><li>Eligible properties may receive one introductory one-month free trial. Trial scope, setup, and start date are confirmed by DesignNetrix.</li><li>Current public monthly prices are displayed on the Pricing page. A signed proposal or order form controls if it specifies different scope, taxes, users, properties, integrations, services, or pricing.</li><li>Annual plans are prepaid for 12 months and receive the displayed annual discount. A custom direct-booking website is included within an agreed scope. Pro Annual also includes an agreed branding and social-media launch package; deliverables, channels, revision limits, and timelines must be recorded in the proposal.</li><li>Subscriptions renew for the selected billing period unless cancelled before renewal in the manner stated on the invoice, order form, or account notice.</li><li>Fees are non-refundable once a paid period begins except where the order form says otherwise or mandatory law requires a remedy. This does not limit non-excludable consumer rights.</li></ul></section>
        <section id="customer"><span>03</span><h2>Customer and user responsibilities</h2><p>Customers must provide accurate account and billing information, keep authorised-user access current, protect credentials, configure the service appropriately, and ensure their use of guest, employee, payment, identification, and payroll information is lawful. Customers remain responsible for notices, consents, record accuracy, statutory filings, tax decisions, employment decisions, and operational actions made using NamiOS.</p><p>You must not misuse the service, attempt unauthorised access, interfere with security or availability, copy or reverse engineer protected software except where law permits, upload malicious content, or use NamiOS for unlawful, deceptive, infringing, or abusive activity.</p></section>
        <section id="data-terms"><span>04</span><h2>Customer data, privacy, and intellectual property</h2><p>Customers retain their rights in data they submit. They grant DesignNetrix the limited rights needed to host, process, secure, back up, transmit, and support that data for the service. DesignNetrix owns NamiOS, its software, interfaces, documentation, brand assets, methods, and improvements, excluding customer content and third-party materials.</p><p>Personal data is handled under the NamiOS Privacy Policy, applicable customer instructions, and any agreed data-processing terms. Aggregated or de-identified operational information may be used to improve reliability, usability, and product decisions where it cannot reasonably identify a person or property.</p></section>
        <section><span>05</span><h2>Third-party services</h2><p>NamiOS may connect with payment gateways, OTAs, messaging services, cloud infrastructure, accounting tools, or other independent services. Their availability, fees, rules, data handling, and performance are controlled by their providers. DesignNetrix is not responsible for a third party’s service, but will use reasonable care when selecting and integrating providers.</p></section>
        <section id="service"><span>06</span><h2>Availability, support, changes, and suspension</h2><p>We aim to provide a dependable service, but maintenance, security work, internet conditions, provider failures, emergencies, or events outside reasonable control may affect availability. Support channels and any specific service levels are those stated in the applicable plan or agreement.</p><p>We may improve, replace, or discontinue features where reasonably necessary. We may suspend access to address security risks, unlawful use, material breach, or overdue payment after reasonable notice where practicable.</p></section>
        <section><span>07</span><h2>Termination</h2><p>Either party may end the subscription as provided in the selected billing plan or order form. A party may terminate for a material breach that is not remedied within a reasonable notice period, or immediately for serious security, insolvency, fraud, or unlawful-use concerns where permitted by law.</p><p>After termination, access ends and customer data will be exported, retained, or deleted according to the agreement, Privacy Policy, lawful retention duties, and normal backup cycles. Fees and obligations accrued before termination remain due.</p></section>
        <section id="liability"><span>08</span><h2>Warranties and liability</h2><p>NamiOS is provided with reasonable skill and care. Except for express commitments and rights that cannot lawfully be excluded, the service is provided without an assurance that every feature will be uninterrupted, error-free, or suitable for every operational, legal, tax, employment, or accounting decision.</p><p>To the extent permitted by Sri Lankan law, neither party is liable for indirect or consequential loss, lost profits, or loss arising from data or decisions outside its reasonable control. Any contractual liability cap will be stated in the applicable order form. Nothing excludes liability that cannot legally be excluded, including liability for fraud or wilful misconduct.</p></section>
        <section id="law"><span>09</span><h2>Governing law and disputes</h2><p>These Terms are governed by the laws of Sri Lanka. The parties will first try in good faith to resolve a dispute through written notice and direct discussion. If it cannot be resolved, the courts of competent jurisdiction in Sri Lanka will have jurisdiction, unless the parties agree another lawful dispute process in writing.</p><p>Mandatory rights and remedies under the Consumer Affairs Authority Act No. 9 of 2003 and applicable directions remain unaffected.</p></section>
        <section className="legal-contact"><span>10</span><h2>Changes and contact</h2><p>We may update these Terms to reflect product, commercial, provider, or legal changes. Material changes will be communicated reasonably before taking effect when required. Continuing to use the service after the effective date constitutes acceptance where permitted by law.</p><p>Questions: <a href="mailto:hello@namios.io?subject=NamiOS%20terms%20question">hello@namios.io</a> · NamiOS by DesignNetrix, Colombo, Sri Lanka.</p></section>
        <div className="legal-reference"><strong>Important</strong><p>The order form, data-processing terms, and any signed service schedule form part of the agreement and take priority over these website Terms where they expressly differ. These public Terms should be reviewed by Sri Lankan counsel before final commercial launch.</p></div>
      </article>
    </div>
  </main>
);

export default TermsPage;
